# docker-compose.yml
version: '3'
services:
  own_image_uploader:
    image: ghcr.io/necrolingus/own_image_uploader:latest
    restart: unless-stopped
    env_file: stack.env
    ports:
      - 3065:3000
    volumes:
      - theuploadfolder:/usr/src/app/uploads

volumes:
  theuploadfolder: 