# docker-compose.yml
version: '3.8'
services:
  own_image_uploader:
    image: ghcr.io/necrolingus/own_image_uploader:latest
    restart: unless-stopped
    env_file: stack.env
    ports:
      - 3065:3000