# docker-compose.yml
version: '3.8'
services:
  own_image_uploader:
    image: dont_email_passwords:latest
    restart: unless-stopped
    env_file: stack.env
    ports:
      - 3065:3000
    volumes:
      - uploads:/usr/src/app

volumes:
  uploads:
